image: docker:stable
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_OPENJDK_MAVEN: maven:3.8.5-jdk-11
  
services:
  - docker:dind

stages:
  - clean
  - build
  - test
  - build-image
  - publish-image
  - deploy

clean:
  image: $IMAGE_OPENJDK_MAVEN
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - mvn clean

build:
  image: $IMAGE_OPENJDK_MAVEN
  stage: build
  script:
    - mvn  package

static-code-analysis:
  image: $IMAGE_OPENJDK_MAVEN
  stage: test
  script:
    - echo "Running Static Code Analysis..."
    - echo "Checking style..."
    

unit-test:
  image: $IMAGE_OPENJDK_MAVEN
  stage: test
  script:
    - echo "Running unit tests..."
    

coverage-test:
  image: $IMAGE_OPENJDK_MAVEN
  stage: test
  needs:
    - job: unit-test
  script:
    - echo "Running coverage tests..."
 
build_image:
  stage: build-image
  environment:
    name: dev
    url: https://dev.abc.com
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/bhanuraina/spring-boot-react-ecs .
    - docker push registry.gitlab.com/bhanuraina/spring-boot-react-ecs
  #when: manual
  #rules:
  #  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
deploy:
  stage: deploy
  environment:
    name: dev
    url: https://dev.abc.com
  image: python:latest
  script:
    - pip install awscli
    - aws ecs update-service --cluster fargate-cluster --service fargate-docker-service --force-new-deployment --region us-east-2
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

